name: Ping

on:
  schedule:
    - cron: '*/12 * * * *'
    
  workflow_dispatch: 

jobs:
  ping: 
    runs-on: ubuntu-latest

    steps:
      - name: Ping ct website
        run:
         curl https://ct12.onrender.com > dev/null
